version: '3.8'

services:
  nginx:
    build: nginx
    restart: always
    volumes:
      - nginx_logs:/var/log/nginx
      - billing_static:/home/app/admin_panel/static
    ports:
      - "5010:5010"  # auth_api
      - "5020:5020"  # billing_app
      - "5555:5555"  # billing_flower
      - "5030:5030"  # notification_api
      - "5601:5601"  # kibana_logging
    networks:
      - movie_network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.0
    hostname: zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    expose:
      - 2181
    networks:
      - movie_network

  kafka:
    image: confluentinc/cp-kafka:7.0.0
    container_name: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    expose:
      - 29092
    ports:
      - "9092:9092"
    networks:
      - movie_network
    depends_on:
      - zookeeper

  filebeat_logging:
    image: elastic/filebeat:7.12.0
    environment:
      ELASTICSEARCH_HOSTS: "http://elastic_logging:9200"
      KIBANA_HOST: "http://kibana_logging"
    volumes:
      - ./filebeat/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro
      - nginx_logs:/var/harvested_logs/nginx:ro
      - auth_logs:/var/harvested_logs/auth:ro
      - billing_logs:/var/harvested_logs/billing:ro
      - event_to_notification_logs:/var/harvested_logs/event_to_notification:ro
      - notification_api_logs:/var/harvested_logs/notification_api:ro
      - notification_sender_logs:/var/harvested_logs/notification_sender:ro
    entrypoint: filebeat -e -strict.perms=false
    networks:
      - movie_network
    depends_on:
      elastic_logging:
        condition: service_healthy
      kibana_logging:
        condition: service_healthy

  elastic_logging:
    image: elasticsearch:7.12.0
    environment:
      xpack.security.enabled: "false"
      bootstrap.memory_lock: "true"
      network.host: 0.0.0.0
      discovery.type: single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: curl -s http://elastic_logging:9200/_cat/health >/dev/null || exit 1
      interval: 5s
      timeout: 20s
      retries: 100
    expose:
      - 9200
    networks:
      - movie_network

  kibana_logging:
    image: kibana:7.12.0
    environment:
      ELASTICSEARCH_URL: http://elastic_logging:9200
      ELASTICSEARCH_HOSTS: '["http://elastic_logging:9200"]'
    healthcheck:
      test: curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'
      interval: 5s
      timeout: 20s
      retries: 100
    expose:
      - 5601
    networks:
      - movie_network
    depends_on:
      elastic_logging:
        condition: service_healthy


volumes:
  billing_static:
    name: billing_static
  nginx_logs:
    name: nginx_logs
  auth_logs:
    name: auth_logs
  billing_logs:
    name: billing_logs
  event_to_notification_logs:
    name: event_to_notification_logs
  notification_api_logs:
    name: notification_api_logs
  notification_sender_logs:
    name: notification_sender_logs


networks:
  movie_network:
    name: movie_network
    driver: bridge
